---
version: '3.1'
services:
  db:
    image: postgres:12.4
    ports:
    - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_DB: abcontrol
      POSTGRES_USER: abcontrol
      POSTGRES_PASSWORD: absecret
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
  adminer:
      image: adminer
      restart: unless-stopped
      ports:
      - 8181:8080
