---
version: '3.1'
services:
  db:
    image: postgres:12.4
    ports:
    - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_DB: {{ POSTGRES_DB }}
      POSTGRES_USER: {{ POSTGRES_USER }}
      POSTGRES_PASSWORD: {{ POSTGRES_PASSWORD }}
    volumes:
      - "./pgdata:/var/lib/postgresql/data"

#  adminer:
#      image: adminer
#      restart: unless-stopped
#      ports:
#      - 8181:8080
