oxidized:
  restart: unless-stopped
  image: oxidized/oxidized:latest
  ports:
    - 8888:8888/tcp
  #environment:
  #  CONFIG_RELOAD_INTERVAL: 600
  volumes:
    - ./etc:/etc/oxidized
    - ./devices.git:/var/lib/oxidized/devices.git
    - ./log:/var/log/oxidized
