---
version: '3.1'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: {{ RABBITMQ_ERLANG_COOKIE }}
      RABBITMQ_DEFAULT_USER: {{ RABBITMQ_USERNAME }}
      RABBITMQ_DEFAULT_PASS: {{ RABBITMQ_PASSWORD }}
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
    - "5672:5672"
    - "15672:15672"
    restart: unless-stopped
